### ISSUE TITLE
Submission did not upload

### ISSUE THREAD

**Issue by HMorrison** [avoorhis/vamps-node.js#29]
"This page isn’t working
vampsdev.jbpc-np.mbl.edu didn’t send any data.
ERR_EMPTY_RESPONSE"

This happened as soon as I tried to validate the submission. 
Will try again.

**Comment by HMorrison** [comment]
![untitled](https://user-images.githubusercontent.com/8506428/44348722-402ccf80-a469-11e8-903c-a46a8cff4b2e.png)

**Comment by annaship** [comment]
Thank you for trying!

**Comment by annaship** [comment]
Domain error with shortgun

Aug 20 11:06:16 bpcweb7 vamps2-nodejs[28873]: /usr/local/www/vampsdev/projects/vamps-node.js/controllers/metadataController.js:590
Aug 20 11:06:16 bpcweb7 vamps2-nodejs[28873]: current_info.target_gene = helpers.findByValueOfObject(CONSTS.TARGET_GENE, "domain", current_info.domain)[0].target_gene;
Aug 20 11:06:16 bpcweb7 vamps2-nodejs[28873]: ^
Aug 20 11:06:16 bpcweb7 vamps2-nodejs[28873]: TypeError: Cannot read property 'target_gene' of undefined

**Comment by HMorrison** [comment]
Tried amplicon submission. Validate took me back to the login page. I'm done with this for today.

**Comment by annaship** [comment]
OK, thank you!

**Comment by annaship** [comment]
"Domain error with shortgun" fixed for "project".
For "dataset" added a dropdown menu with dna region choices

**Comment by annaship** [comment]
The original issue is fixed.
